-- Run once in Supabase Dashboard > SQL Editor.
-- Replaces placeholder cards with PDF-based cards. Video references are omitted.

begin;
alter table public.training_cards add column if not exists sections jsonb not null default '[]'::jsonb;
delete from public.training_cards;

insert into public.training_cards (topic, title, body, sections) values
($q$First aid kit$q$,$q$Making a Cat and Dog First Aid Kit$q$,$q$Keep a properly sized muzzle, safe transport items, snug non-latex disposable gloves, pet-sized nail clippers, styptic powder, a slip lead, a quick-read thermometer, wound-care items, and updated emergency contact information in the kit.$q$,jsonb_build_array(jsonb_build_object('heading','Key details','content',$q$Cat muzzles may cover the nose, mouth, and eyes; covering the eyes can help a cat remain calm. Small pets may be transported in an appropriately sized carrier; large dogs may need a sling, board, or human help. A large towel can serve as a makeshift sling, support, or warmth.$q$))),
($q$First aid kit$q$,$q$First Aid Kit: Wound Care and Disaster Readiness$q$,$q$Keep items needed to clean, cover, and protect wounds. Check expiration dates regularly and replace expired items.$q$,jsonb_build_array(jsonb_build_object('heading','Wound-care items','content',$q$The notes list electric clippers, hydrogen peroxide or isopropyl alcohol, gauze squares and roll gauze, triple antibiotic ointment, sterile water-based lubrication jelly, adhesive and non-adhesive tape, bandage scissors, and sterile eye wash.$q$),jsonb_build_object('heading','Disaster kit','content',$q$Keep veterinary information, pet-friendly lodging or care options, medications, food and containers, bedding, toys, and treats ready in a convenient location with the first-aid kit.$q$))),
($q$Safety$q$,$q$Aggressive Dog Safety$q$,$q$Before approaching a pet in an emergency, make sure the scene is safe and that you are comfortable approaching. Even docile dogs can become aggressive when afraid or in pain.$q$,jsonb_build_array(jsonb_build_object('heading','Possible signs','content',$q$Growling; showing teeth; raised fur on the back and shoulders; cowering or moving away; urinating; and lip smacking. This list is not complete.$q$),jsonb_build_object('heading','Safety response','content',$q$Do not approach if you see aggression signs until help arrives or the animal calms down. A Gentle Leader, slip lead, appropriately sized muzzle, soft material, or towel may help in situations described in the notes; skip muzzling if it increases agitation.$q$))),
($q$Safety$q$,$q$Aggressive Cat Safety$q$,$q$If you are unsure how to safely approach an aggressive cat, do not approach until you get help or the cat calms down.$q$,jsonb_build_array(jsonb_build_object('heading','Possible signs','content',$q$Hissing or yowling; flattened or pinned-back ears; raised fur along the spine; flicking or moving tail; and crouching or moving away.$q$),jsonb_build_object('heading','Handling options','content',$q$The notes describe a towel wrap, a disassembled carrier, and a cat muzzle. A towel should cover the cat completely, including the head, before lifting the wrapped cat.$q$))),
($q$Observation$q$,$q$Knowing What's Normal for Your Pet$q$,$q$Knowing what is normal for your individual pet helps you recognize what is abnormal. Notice subtle changes so problems may be identified earlier and described to a veterinarian.$q$,jsonb_build_array(jsonb_build_object('heading','Monitor','content',$q$The notes emphasize becoming familiar with normal appearance, behavior, eating and drinking, elimination, and vital signs for your own pet.$q$))),
($q$Observation$q$,$q$Cat and Dog Behavior Changes$q$,$q$Behavior changes can be an early sign that something is wrong. Compare behavior with what is normal for your own pet and investigate further when you notice a change.$q$,jsonb_build_array(jsonb_build_object('heading','Examples','content',$q$Examples in the notes include a dog that no longer greets you as usual, a cat whose usual behavior changes, and a pet that leaves food uneaten when it normally eats eagerly.$q$))),
($q$Vital signs$q$,$q$Cat and Dog Pulse Rate$q$,$q$Measure pulse while the pet is resting so measurements are consistent. The notes describe locating the femoral artery on the inside of the thigh and counting pulsations.$q$,jsonb_build_array(jsonb_build_object('heading','Why consistency matters','content',$q$Activity, stress, and anxiety can change measurements. Compare readings with your pet's normal resting values.$q$))),
($q$Vital signs$q$,$q$Cat and Dog Gum Color$q$,$q$Become familiar with your pet's normal gum color. The notes state that white, pale pink, blue, or other abnormal colors should prompt assessment of the rest of the pet.$q$,jsonb_build_array(jsonb_build_object('heading','When gums look abnormal','content',$q$Check other vital signs and how the pet is doing or feeling. The notes direct attention to abnormalities rather than relying on gum color alone.$q$))),
($q$Vital signs$q$,$q$Cat and Dog Breathing Rate$q$,$q$Measure breathing while the pet is resting because activity, stress, and anxiety can skew the number. Watch the rise and fall of the chest and count breaths.$q$,jsonb_build_array(jsonb_build_object('heading','Normal observation','content',$q$The chest should expand and contract; slight abdominal movement and panting are described as normal breathing observations in the notes.$q$))),
($q$Vital signs$q$,$q$Cat and Dog Temperature$q$,$q$Temperature is a key vital sign. The notes describe using a thermometer rectally, waiting for the reading, recording it, and deciding whether there is cause for concern.$q$,jsonb_build_array(jsonb_build_object('heading','Measurement reminder','content',$q$Use an animal thermometer and follow the notes' instructions carefully. The notes warn against relying on an animal's nose moisture to judge wellness.$q$))),
($q$Illness$q$,$q$Introduction to Cat and Dog Illness$q$,$q$The notes reject the idea that nose moisture alone tells you whether a pet is well. Monitor the pet's overall behavior and vital signs.$q$,jsonb_build_array(jsonb_build_object('heading','Core approach','content',$q$Know what is normal for the pet, notice abnormalities, and gather useful information for the veterinarian.$q$))),
($q$Illness$q$,$q$Cat and Dog Vomiting Care$q$,$q$Vomiting is common and may or may not be problematic. The notes direct you to determine how often it is happening and whether other behaviors have changed.$q$,jsonb_build_array(jsonb_build_object('heading','Observe','content',$q$Investigate why vomiting may be occurring by considering frequency and other signs or behavior changes.$q$))),
($q$Illness$q$,$q$Cat and Dog Diarrhea$q$,$q$Diarrhea is common in dogs and cats and can occur with vomiting. The notes direct attention to the pet's overall condition and other abnormalities.$q$,jsonb_build_array(jsonb_build_object('heading','Monitor','content',$q$Consider how often the problem occurs and whether other behavior or vital-sign abnormalities are present.$q$))),
($q$Illness$q$,$q$Cat and Dog Peeing Problems$q$,$q$Monitor urinary habits at home so you know what is normal and can recognize when swift action is needed.$q$,jsonb_build_array(jsonb_build_object('heading','Urgent signs','content',$q$The notes describe signs such as straining, repeated attempts to urinate, crying, blood, or a firm swollen midsection. Seek veterinary care immediately when these are present, especially with obvious urinary problems.$q$))),
($q$Illness$q$,$q$Loss of Appetite in Pets$q$,$q$Loss of appetite can have many causes. Start by considering whether the food itself may be a problem and whether the pet has other abnormalities.$q$,jsonb_build_array(jsonb_build_object('heading','What to note','content',$q$The notes direct you to consider food quality or a possible recall, replace food from a different batch if needed, and decide whether veterinary care is warranted based on other signs.$q$))),
($q$Illness$q$,$q$Lethargic Dogs and Cats$q$,$q$Lethargy is a vague sign that can have many causes. Take the pet's vital signs and look for behavioral changes.$q$,jsonb_build_array(jsonb_build_object('heading','At-home role','content',$q$If the pet is eating and drinking and vital signs are normal, the notes say to watch the lethargy for a while when there is a reason for it. Record recent vital signs and behaviors, and do not give medications.$q$))),
($q$Illness$q$,$q$Cat and Dog Weakness or Collapse$q$,$q$Weakness can include reduced exercise, reduced use of legs, or holding the head lower than normal. Take note of exactly what you observe for the veterinarian.$q$,jsonb_build_array(jsonb_build_object('heading','Information to record','content',$q$Record what is happening, signs noticed, when they began, and any changes in behavior or vital signs.$q$))),
($q$Neurologic emergencies$q$,$q$Cat and Dog Seizures$q$,$q$A seizure is abnormal activity in the brain. During a seizure, do not restrain the pet; instead, prevent injury from falls or stairs and observe what occurs.$q$,jsonb_build_array(jsonb_build_object('heading','After a seizure','content',$q$Record what happened so you can inform the veterinarian. The notes emphasize remaining calm and monitoring the pet's temperature, including keeping it below 104°F.$q$))),
($q$Temperature emergencies$q$,$q$Body Temperature Emergencies$q$,$q$The notes distinguish internal changes in the brain's temperature set point from external temperature changes. The appropriate response differs between these situations.$q$,jsonb_build_array(jsonb_build_object('heading','Rule of thumb','content',$q$Observe whether the pet is trying to warm or cool itself, and use that behavior together with the situation and vital signs to guide your response.$q$))),
($q$Temperature emergencies$q$,$q$Hypothermia$q$,$q$Hypothermia requires gentle warming for comfort during transport. The notes caution that warming too aggressively or quickly can be problematic and should occur under veterinary care.$q$,jsonb_build_array(jsonb_build_object('heading','First response','content',$q$Wrap the pet in a large towel or blanket to help the body rewarm naturally while traveling to a veterinary facility.$q$))),
($q$Temperature emergencies$q$,$q$Hyperthermia (Heat Stroke / Sun Stroke)$q$,$q$Heat stroke can occur in hot environments or with overexertion. Dogs unable to pant effectively, including short-snouted dogs, may be at risk.$q$,jsonb_build_array(jsonb_build_object('heading','Urgent sign and response','content',$q$The notes identify a rectal temperature of 105°F or greater as an early sign of heat stroke and direct immediate cooling. Seek veterinary care as soon as possible.$q$))),
($q$Temperature emergencies$q$,$q$Cat and Dog Fever$q$,$q$Fever differs from heat stroke because the brain's set point changes with an internal cause. The notes say not to cool a pet that is combating fever.$q$,jsonb_build_array(jsonb_build_object('heading','When to escalate','content',$q$If fever occurs with additional abnormalities, seek immediate veterinary care. The notes advise erring on the side of caution.$q$))),
($q$Shock$q$,$q$Cat and Dog Shock Assessment$q$,$q$Be alert for shock in sick or injured pets. Changes in pulse rate, gum color, and temperature of ear, toe, or tail tips can be important signs.$q$,jsonb_build_array(jsonb_build_object('heading','Assessment','content',$q$The notes describe circulatory shock as compromised blood circulation that may leave extremities cool. If multiple concerning signs are present, transport the pet for veterinary care.$q$))),
($q$Bleeding$q$,$q$Cat and Dog Bleeding Care$q$,$q$Before approaching an injured animal, make sure the scene is safe and watch for aggression. Pain can cause a pet to lash out.$q$,jsonb_build_array(jsonb_build_object('heading','Control bleeding','content',$q$Use gauze and direct pressure. For a wound that soaks through, continue adding gauze until bleeding is controlled or the bandage is secured. Arterial bleeding can be life-threatening.$q$))),
($q$Bleeding$q$,$q$Cat and Dog Nail Bleeding$q$,$q$Styptic powder is intended to stop nail bleeding. Keep it available, especially when clipping nails at home.$q$,jsonb_build_array(jsonb_build_object('heading','Kit reminder','content',$q$Use clippers sized appropriately for the pet and keep a product for nail bleeding in the first-aid kit.$q$))),
($q$Wounds$q$,$q$Cat and Dog Wound Treatment$q$,$q$For injuries, have materials ready to clean, cover, and protect a wound. Electric clippers can improve visibility by trimming fur around an injury.$q$,jsonb_build_array(jsonb_build_object('heading','Supplies noted','content',$q$The notes list gauze, tape, bandage scissors, hydrogen peroxide or isopropyl alcohol, antibiotic ointment, lubrication jelly, and sterile eye wash among wound-care supplies.$q$))),
($q$Lameness$q$,$q$Lame Dog and Cat Care$q$,$q$Make sure the scene is safe and watch for aggression before assessing a lame pet. Begin examining legs at the toes and move upward, gently checking for lumps, bumps, and pain response.$q$,jsonb_build_array(jsonb_build_object('heading','When a source is found','content',$q$The notes describe applying an ice pack in a resealable bag directly to the painful area for 10 to 15 minutes.$q$))),
($q$Lameness$q$,$q$Severe Pet Lameness$q$,$q$Lameness without an injury or pain response may be related to an underlying neurologic problem. Severe lameness requires careful assessment and veterinary attention.$q$,jsonb_build_array(jsonb_build_object('heading','Observe','content',$q$Note whether the pet can use limbs, shows pain, or has trouble standing or walking, and share those observations with the veterinarian.$q$))),
($q$Burns$q$,$q$Cat and Dog Burn Care$q$,$q$Burns can involve secondary infection, fluid loss, and electrolyte imbalances. The notes state that most pets with a burn injury should be evaluated by a veterinarian.$q$,jsonb_build_array(jsonb_build_object('heading','First response','content',$q$Ensure the scene is safe; check vital signs with special attention to breathing; cool the burn area with cool water; wrap the pet in a blanket or towel; and transport for further care.$q$))),
($q$Trauma$q$,$q$Cat and Dog Fractures and Spinal Injuries$q$,$q$Trauma can be severe and should be taken seriously. Transport the pet to a veterinarian quickly and as safely as possible.$q$,jsonb_build_array(jsonb_build_object('heading','Spinal concerns','content',$q$The notes describe pain with movement of the head, neck, or trunk and trouble moving limbs as possible spinal-injury signs. Check vital signs and take special care during movement.$q$))),
($q$Transport$q$,$q$Safe Moving of Injured Dogs and Cats$q$,$q$Once it is safe to approach, an animal in pain may need a muzzle before transport. Smaller animals may be lifted if doing so is safe; larger animals may need a helper and a blanket or board.$q$,jsonb_build_array(jsonb_build_object('heading','Blanket transport','content',$q$Place the blanket in front of the pet, get feet and legs onto it first, then lift gently with coordinated help.$q$))),
($q$Poisoning$q$,$q$Recognizing Cat and Dog Poisoning$q$,$q$Possible poisoning signs include drooling, vomiting, diarrhea, stumbling, muscle twitching or tremors, depression, hyperactivity, seizures, unconsciousness, and bleeding of the mouth or skin.$q$,jsonb_build_array(jsonb_build_object('heading','Be prepared','content',$q$If poisoning is suspected, contact a veterinarian or animal poison control and have useful information about the pet and suspected toxin ready.$q$))),
($q$Poisoning$q$,$q$Common Pet Poisons$q$,$q$Potential sources include prescription and over-the-counter medications, human foods, and house plants. Do not assume an over-the-counter medication is safe for pets.$q$,jsonb_build_array(jsonb_build_object('heading','Prevention','content',$q$Store potential toxins safely. When in doubt about an exposure, consult a veterinarian.$q$))),
($q$Poisoning$q$,$q$Dangerous Cat Poisons$q$,$q$The notes identify flea medications as a concern for cats and state that labels may not always make toxicity clear.$q$,jsonb_build_array(jsonb_build_object('heading','Prevention and response','content',$q$Be diligent before purchasing flea medication for a cat. If a toxic exposure is suspected, seek veterinary or poison-control guidance.$q$))),
($q$Poisoning$q$,$q$Making a Cat or Dog Vomit$q$,$q$Inducing vomiting is not always recommended. The notes direct you to contact Animal Poison Control or a local veterinarian before doing so.$q$,jsonb_build_array(jsonb_build_object('heading','Course note','content',$q$When animal poison control gives the go-ahead, the notes describe 1 teaspoon of 3% hydrogen peroxide per 10 pounds of body weight, with one repeat dose if needed. Do not induce vomiting without that guidance.$q$))),
($q$Eye care$q$,$q$Pet Eye Washing$q$,$q$Sterile eye wash can be used to flush an eye when the pet has an eye injury or foreign material in the eye.$q$,jsonb_build_array(jsonb_build_object('heading','Technique','content',$q$The notes describe keeping the pet secure, aiming the eye wash, squeezing to spray, and flushing again as needed.$q$))),
($q$Bites and stings$q$,$q$Cat and Dog Snake Bites$q$,$q$Do not put yourself in danger trying to identify a snake. If safe, a picture may help because antivenom depends on snake type.$q$,jsonb_build_array(jsonb_build_object('heading','Veterinary care','content',$q$Snake-bite signs may not be obvious. If a pet has been around a venomous snake, the notes direct veterinary monitoring as soon as possible, generally for a day or two.$q$))),
($q$Bites and stings$q$,$q$Cat and Dog Spider Bites$q$,$q$Venomous spider bites are uncommon and may be difficult to identify unless the interaction was witnessed. Brown recluse bites can cause pain and local tissue damage.$q$,jsonb_build_array(jsonb_build_object('heading','Treatment','content',$q$The notes describe supportive care and veterinary evaluation for suspected venomous spider bites.$q$))),
($q$Allergies$q$,$q$Allergies$q$,$q$Sudden mild allergic-reaction signs can include pain, facial swelling, scratching, hives, and vomiting. Check vital signs to help guide the next course of action.$q$,jsonb_build_array(jsonb_build_object('heading','Serious concern','content',$q$The notes list light pink or dark red gums, fast pulse, fast breathing, weakness, and collapse as concerning signs of anaphylactic shock. Transport the pet to a veterinarian as soon as possible and do not give medication without guidance.$q$))),
($q$Respiratory$q$,$q$Cat and Dog Respiratory Distress$q$,$q$Respiratory distress can include breathing harder than normal at rest, flaring nostrils, use of neck or abdominal muscles, coughing during expiration, spread elbows, louder or faster breathing, and discolored gums.$q$,jsonb_build_array(jsonb_build_object('heading','Response','content',$q$The notes state that there is not much to do at home for respiratory distress and direct getting the pet to a veterinarian as soon as possible.$q$))),
($q$Choking$q$,$q$Cat and Dog Choking (Conscious)$q$,$q$Stay calm and assess the pet. If the pet is conscious, inspect the mouth carefully for an object without pushing it farther in.$q$,jsonb_build_array(jsonb_build_object('heading','Technique','content',$q$The notes describe alternating abdominal thrusts and back blows, checking the mouth in between, until the object is dislodged or the pet becomes unconscious. Smaller dogs and cats use a modified technique.$q$))),
($q$Choking$q$,$q$Cat and Dog Choking (Unconscious)$q$,$q$For an unconscious pet, first check the mouth for an object lodged in the throat, taking care not to get bitten or push the object farther in.$q$,jsonb_build_array(jsonb_build_object('heading','Next steps','content',$q$The notes describe rescue breaths, abdominal thrusts or back blows, pulse checks every two cycles, and CPR if no pulse is found.$q$))),
($q$Near drowning$q$,$q$Pet Near Drowning$q$,$q$Remove a submerged pet completely from the water and position the pet to help water drain through the nose and mouth.$q$,jsonb_build_array(jsonb_build_object('heading','Follow-up','content',$q$The notes direct veterinary evaluation even when the pet does not seem to have problems after submersion.$q$))),
($q$CPR$q$,$q$Pet CPR Introduction$q$,$q$CPR consists of rescue breaths and high-quality chest compressions. Time matters because the brain and other important tissues can suffer damage after only a few minutes without oxygenated blood flow.$q$,jsonb_build_array(jsonb_build_object('heading','Before CPR','content',$q$The notes list loss of consciousness, no normal breathing or agonal breaths, and no pulse as the three conditions to check before providing CPR.$q$))),
($q$CPR$q$,$q$Cat and Dog CPR Demonstration$q$,$q$For CPR, find the center of the chest in larger pets or the heart area in smaller pets, where the elbow meets the chest. Lock elbows and position directly above the compression spot.$q$,jsonb_build_array(jsonb_build_object('heading','Cycle','content',$q$Compress to one-third to one-half the chest depth, allow full recoil, and use 100 to 120 compressions per minute. The notes describe 30 compressions, 2 rescue breaths, and a pulse check before repeating if no pulse is detected.$q$))),
($q$End of life$q$,$q$Pet End-of-Life$q$,$q$The notes define euthanasia as a good death. In most situations, a veterinarian places a catheter in the pet's leg and administers an overdose of an anesthetic drug.$q$,jsonb_build_array(jsonb_build_object('heading','What the notes describe','content',$q$The medication causes the pet to go to sleep as if going under for a surgical procedure. The notes present this as a veterinarian-led process.$q$)));

-- Add the matching Pro Tip or Warning from each course summary as a labeled card section.
-- These are intentionally kept separate so the important guidance is easy to spot in Discord.
with card_notes (title, heading, content) as (
  values
    ($q$Making a Cat and Dog First Aid Kit$q$, $q$Pro tip$q$, $q$Keep the kit and disaster kit together in a convenient location, with current contact details for a regular veterinarian, local emergency veterinarian, and animal poison control. This saves time and reduces stress in an emergency.$q$),
    ($q$First Aid Kit: Wound Care and Disaster Readiness$q$, $q$Warning$q$, $q$Check expiration dates for all first-aid-kit items regularly; discard and replace expired items.$q$),
    ($q$Aggressive Dog Safety$q$, $q$Warning$q$, $q$If you see aggression signs or do not feel it is safe to approach, wait for help or for the dog to calm down. If muzzling increases agitation, skip it and prioritize your own safety.$q$),
    ($q$Aggressive Cat Safety$q$, $q$Pro tip$q$, $q$Using a disassembled carrier can make it easier to place a cat inside than trying to push the cat through a small opening. Covering a cat's eyes with a muzzle can also help the cat calm down.$q$),
    ($q$Knowing What's Normal for Your Pet$q$, $q$Warning$q$, $q$Pets may hide problems for a long time. Notice subtle changes early, before a hidden problem becomes severe.$q$),
    ($q$Cat and Dog Behavior Changes$q$, $q$Pro tip$q$, $q$Before deciding a behavior is abnormal, first understand what is normal for that individual pet. Changes in eating, social, or bathroom habits should be investigated further.$q$),
    ($q$Cat and Dog Pulse Rate$q$, $q$Pro tip$q$, $q$Measure the pulse when the pet is resting and calm. A measurement taken at the veterinarian can differ because stress can affect vital signs; when checking the femoral artery, curl your hand under the top leg to help the pet remain calm.$q$),
    ($q$Cat and Dog Gum Color$q$, $q$Warning$q$, $q$Focus on the larger gum areas rather than normal pigmented spots. White, pale pink, blue, or other abnormal gum colors call for checking other vital signs, behavior, and how the pet is doing.$q$),
    ($q$Cat and Dog Breathing Rate$q$, $q$Warning$q$, $q$A resting breathing rate faster than 40 breaths per minute can be concerning, especially when it is higher than that pet's usual rate. Check other vital signs and how the pet is feeling and behaving.$q$),
    ($q$Cat and Dog Temperature$q$, $q$Warning$q$, $q$Wash, sanitize, or disinfect the thermometer after using it. A helper can distract, talk to, or pet the animal while keeping the pet calm during temperature measurement.$q$),
    ($q$Introduction to Cat and Dog Illness$q$, $q$Pro tip$q$, $q$Do not use nose moisture or temperature alone to judge whether a pet is well. Assess the pet's overall behavior and vital signs.$q$),
    ($q$Cat and Dog Vomiting Care$q$, $q$Warning$q$, $q$Bloat or GDV is a serious emergency. Seek veterinary care immediately if you suspect it.$q$),
    ($q$Cat and Dog Diarrhea$q$, $q$Warning$q$, $q$Bloody diarrhea is not routine. A sudden severe case of bloody diarrhea can be life-threatening and requires immediate veterinary care.$q$),
    ($q$Cat and Dog Peeing Problems$q$, $q$Warning$q$, $q$Straining to urinate without producing urine can be life-threatening and requires immediate veterinary care. Do not restrict water if the pet is drinking more; that can lead to dehydration.$q$),
    ($q$Loss of Appetite in Pets$q$, $q$Pro tip$q$, $q$If a pet stops eating, check vital signs and whether behavior is otherwise normal. If the pet otherwise appears normal, consider whether the food itself could be a problem.$q$),
    ($q$Lethargic Dogs and Cats$q$, $q$Warning$q$, $q$Do not give a lethargic pet medication, including an all-natural product, because it can complicate the situation. Record vital signs, behavior, eating and drinking, and when observations were made.$q$),
    ($q$Cat and Dog Weakness or Collapse$q$, $q$Pro tip$q$, $q$Tell the veterinarian as much as possible about what happened, when it began, and what changed. More information helps the veterinarian assess the pet.$q$),
    ($q$Cat and Dog Seizures$q$, $q$Warning$q$, $q$Never put your hand in or around a pet's mouth during a seizure, and do not restrain the pet. A seizure lasting more than five minutes or multiple seizures within 24 hours is an emergency; keep the pet's temperature below 104 degrees F.$q$),
    ($q$Body Temperature Emergencies$q$, $q$Pro tip$q$, $q$Internal causes can change the brain's temperature set point, while external exposure can change body temperature without changing that set point. The response differs: help the pet warm or cool according to what the pet's body is trying to do.$q$),
    ($q$Hypothermia$q$, $q$Warning$q$, $q$Do not actively or rapidly warm a pet after a hypothermia emergency. Wrap the pet to prevent further heat loss and get veterinary care as soon as possible.$q$),
    ($q$Hyperthermia (Heat Stroke / Sun Stroke)$q$, $q$Warning$q$, $q$A rectal temperature of 105 degrees F or greater is an early heat-stroke sign. Begin cooling immediately and seek veterinary care as soon as possible.$q$),
    ($q$Cat and Dog Fever$q$, $q$Warning$q$, $q$Do not give medications for fever without veterinary guidance. Human medications such as aspirin and acetaminophen may harm pets, and acetaminophen is toxic to cats.$q$),
    ($q$Cat and Dog Shock Assessment$q$, $q$Warning$q$, $q$Shock is very serious. If several concerning signs occur together, transport the pet to a veterinarian as soon as possible; at home, there is little that can be done.$q$),
    ($q$Cat and Dog Bleeding Care$q$, $q$Pro tip$q$, $q$Hold direct pressure with gauze for at least five minutes before checking. Lift gauze carefully so you do not disturb a forming clot; if bleeding continues, add gauze on top rather than removing the existing gauze.$q$),
    ($q$Cat and Dog Nail Bleeding$q$, $q$Pro tip$q$, $q$Keep appropriately sized nail clippers and a product for nail bleeding, such as styptic powder, in the first-aid kit.$q$),
    ($q$Cat and Dog Wound Treatment$q$, $q$Warning$q$, $q$Watch for a bandage that is too tight: toes may splay or swell. Remove the bandage, reapply it more loosely, and check the wound daily for signs of infection.$q$),
    ($q$Lame Dog and Cat Care$q$, $q$Warning$q$, $q$A pet in pain may turn, whimper, or try to bite during an examination. If pain cannot be controlled at home, or lameness persists for a couple of days or worsens, seek veterinary care; do not use unapproved medication.$q$),
    ($q$Severe Pet Lameness$q$, $q$Warning$q$, $q$Severe lameness or signs of a neurologic problem require immediate veterinary care. Minimize movement during transport so a possible injury or condition is not made worse.$q$),
    ($q$Cat and Dog Burn Care$q$, $q$Warning$q$, $q$Burns are not injuries to take lightly. A larger or deeper burn, including blistering or charring, needs veterinary care as soon as possible; the notes say a veterinary visit will almost always be warranted.$q$),
    ($q$Cat and Dog Fractures and Spinal Injuries$q$, $q$Warning$q$, $q$Transport to a veterinarian quickly but safely. Take extra care during loading and minimize movement of the injured area so injuries are not made worse.$q$),
    ($q$Safe Moving of Injured Dogs and Cats$q$, $q$Pro tip$q$, $q$For a pet injured by a vehicle, make the road scene safe before approaching. Position your vehicle to block traffic if possible and use headlights and hazard lights to alert others.$q$),
    ($q$Recognizing Cat and Dog Poisoning$q$, $q$Pro tip$q$, $q$If poisoning is suspected, contact a veterinarian or Animal Poison Control promptly. Have details ready about the substance, amount possibly ingested, and the pet; keep poison-control contact information in the first-aid kit.$q$),
    ($q$Common Pet Poisons$q$, $q$Warning$q$, $q$Never give a pet medication that was not prescribed specifically for that pet and purpose. Do not assume over-the-counter medication or human food is safe; when in doubt, consult a veterinarian.$q$),
    ($q$Dangerous Cat Poisons$q$, $q$Warning$q$, $q$Flea medications containing pyrethrins or permethrin can be severely toxic to cats. Do not assume a product is safe because the label lacks a warning; consult Animal Poison Control or a veterinarian before bathing a cat after a suspected topical exposure.$q$),
    ($q$Making a Cat or Dog Vomit$q$, $q$Warning$q$, $q$Do not induce vomiting without guidance from Animal Poison Control or a veterinarian. If it is recommended, ensure the pet is breathing normally, fully conscious, and not depressed or overly anxious before attempting it.$q$),
    ($q$Pet Eye Washing$q$, $q$Pro tip$q$, $q$Eye flushing can be messy and uncomfortable or anxiety-provoking for the pet, but the notes state that it can make a meaningful difference in the pet's eye comfort.$q$),
    ($q$Cat and Dog Snake Bites$q$, $q$Warning$q$, $q$Do not put yourself in danger to identify a snake or take a photo. Even without obvious bite signs after contact with a snake, get veterinary care; monitor behavior and vital signs for abnormalities.$q$),
    ($q$Cat and Dog Spider Bites$q$, $q$Pro tip$q$, $q$Venomous spider bites are uncommon and may be difficult to identify unless the interaction was witnessed. Suspected bites in the notes call for supportive care and veterinary evaluation.$q$),
    ($q$Allergies$q$, $q$Warning$q$, $q$If allergy signs worsen or do not improve within 30 to 60 minutes after veterinarian-recommended Benadryl, seek veterinary evaluation right away. Do not give medication without veterinary instruction when signs are serious.$q$),
    ($q$Cat and Dog Respiratory Distress$q$, $q$Warning$q$, $q$Abdominal muscles actively flexing with each breath is not normal and is a serious sign of labored breathing. Sudden increased work of breathing at rest requires veterinary care as soon as possible.$q$),
    ($q$Cat and Dog Choking (Conscious)$q$, $q$Warning$q$, $q$Stay calm. When checking the mouth, take care not to get bitten or push the object farther in. Gauze or a shirt sleeve can help grip a slippery tongue.$q$),
    ($q$Cat and Dog Choking (Unconscious)$q$, $q$Warning$q$, $q$An unconscious pet can still bite inadvertently, and an object can still be pushed farther in. After an object is dislodged, the notes advise veterinary evaluation because the lungs or throat may have been injured.$q$),
    ($q$Pet Near Drowning$q$, $q$Warning$q$, $q$Even if the pet appears fine after a near-drowning, swallowed water can cause complications such as an electrolyte imbalance. Seek veterinary evaluation as soon as possible.$q$),
    ($q$Pet CPR Introduction$q$, $q$Warning$q$, $q$Time matters in CPR. Agonal or gasping breaths are not normal breathing; if the pet is unconscious, not breathing normally, and no pulse is quickly found, do not delay CPR efforts.$q$),
    ($q$Cat and Dog CPR Demonstration$q$, $q$Pro tip$q$, $q$Lock your elbows and use your body weight for compressions. Allow full chest recoil after every compression, limit interruptions, and switch roles every two minutes when two people are available.$q$),
    ($q$Pet End-of-Life$q$, $q$Pro tip$q$, $q$Discuss quality-of-life decisions and available options with a veterinarian. The notes also encourage seeking support resources and taking care of yourself during grief.$q$)
)
update public.training_cards as cards
set sections = coalesce(cards.sections, '[]'::jsonb) || jsonb_build_array(
  jsonb_build_object('heading', card_notes.heading, 'content', card_notes.content)
)
from card_notes
where cards.title = card_notes.title;

commit;
