-- Run this once in Supabase Dashboard > SQL Editor, after running
-- allow-variable-choice-counts.sql. This replaces every existing question.
-- It preserves employee profiles, points, and streaks.
-- If a daily question is currently posted, delete that Discord message first.

begin;

delete from public.question_answers;
delete from public.question_sessions;
delete from public.quiz_runs;
delete from public.questions;

insert into public.questions (prompt, options, correct_option, explanation, topic) values
-- PNG question bank (answer keys are encoded in the file names)
($q$You are about to perform CPR on your dog or cat. What is the appropriate rate of compressions?$q$, jsonb_build_array($q$150-200 per minute$q$,$q$100-120 per minute$q$,$q$50-100 per minute$q$,$q$175-200 per minute$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Where do you measure a pet's pulse?$q$, jsonb_build_array($q$On the inside of the front legs, the brachial artery$q$,$q$On the side of the neck, the carotid artery$q$,$q$On the inside of the back leg, the femoral artery$q$,$q$At the tip of the tail$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the difference between a pet first aid kit and a disaster preparedness kit?$q$, jsonb_build_array($q$A first aid kit is important, a disaster preparedness kit is not$q$,$q$A first aid kit has tools needed to help a pet who is injured. A disaster preparedness kit has supplies, information and a plan of action for the pet in the case of a major disaster.$q$,$q$They are nearly identical; however, a disaster kit is saved for only times of disaster$q$,$q$A first aid kit has the supplies for basic injuries. A disaster preparedness kit has the supplies to help for a major injury.$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$If you know first aid but you are uncomfortable treating your pet, you should...$q$, jsonb_build_array($q$Try anyway$q$,$q$Go to your neighbor to see if they can help$q$,$q$Review course materials and come back to the issue when you're more comfortable$q$,$q$Consult your veterinarian, using your knowledge from the course to give them as much information as possible$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$You walk into the living room to see that your dog has collapsed on the floor and is unconscious. You feel a pulse, and you see torn up remnants of one of your throw pillows, making you assume the dog is choking on pillow innards. What are your first steps?$q$, jsonb_build_array($q$Deliver a rescue breath. If it doesn't go in, try to dislodge the blockage by doing abdominal thrusts.$q$,$q$Look into the mouth for the blockage. If you can see it, pull it out and then cycle between rescue breaths and abdominal thrusts.$q$,$q$Look in the mouth to see if you can reach the object. If you can, pull it out and begin CPR.$q$,$q$Attempt abdominal thrusts in order to dislodge the block$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your pet has been running around outside a long time on a hot day. Shortly after you let them in, you notice they are still panting heavily and are very lethargic. You take the temperature and their temperature is 105. Your pet could be experiencing...$q$, jsonb_build_array($q$Fever$q$,$q$Hyperthermia / Heat stroke$q$,$q$Exhaustion$q$,$q$Flu$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the first thing you should do when responding to a first aid situation with a pet?$q$, jsonb_build_array($q$Make sure it is safe to approach the pet and the scene$q$,$q$Check your pet's vital signs$q$,$q$Grab your pet and get them to your car to take them to the vet$q$,$q$Stay away from your pet at all times$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$You notice your dog breathing heavily with nostrils flaring. The neck muscles are engaging on inspiration, and the abdominal muscles engage on exhalation. What are these symptoms of?$q$, jsonb_build_array($q$Dehydration$q$,$q$Arterial bleeding$q$,$q$Lethargy$q$,$q$Respiratory distress$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$You see your golden retriever looking anxious, pawing at her face, and struggling to breathe. You quickly check her gums and notice they appear bluish gray. What should you do next?$q$, jsonb_build_array($q$Go immediately into back blows, just behind the shoulder blades$q$,$q$Using gauze, grasp the tongue and carefully check for an object in the mouth$q$,$q$Place your fist in the soft part of her belly and begin abdominal thrusts$q$,$q$Do nothing, but monitor her closely$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$You come into the room and find your pet cat unconscious. You do not feel a pulse and do not see it breathing. What cycle of steps should you perform?$q$, jsonb_build_array($q$20 chest compressions, 2 rescue breaths, check pulse. If no pulse is present, then repeat.$q$,$q$30 chest compressions, 1 rescue breath, repeat$q$,$q$1 rescue breath, 30 chest compressions, check pulse. If no pulse is present, then repeat.$q$,$q$30 chest compressions, 2 rescue breaths, check pulse. If no pulse is present, then repeat.$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your pet has a minor scrape and is bleeding a little. You should...$q$, jsonb_build_array($q$Use your gauze to dab at the bleeding until it stops$q$,$q$Use your gauze to wipe blood away from the wound until it stops bleeding$q$,$q$Immediately take your pet to the vet. This is an emergency.$q$,$q$Place gauze on the wound and hold it for 5 minutes until the bleeding stops$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your favorite pet has suddenly lost its appetite, though it's usually quite the voracious eater. You should first...$q$, jsonb_build_array($q$Get the pet moving to work up its appetite$q$,$q$Skip the meal$q$,$q$Try to feed it something else$q$,$q$Schedule an appointment with your vet$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your pet is urinating 6 or 7 times a day. What should you do first?$q$, jsonb_build_array($q$Cut back on its water intake$q$,$q$Determine whether or not this is normal$q$,$q$Take its vitals and examine it for unhealthy behavior$q$,$q$Increase its daily physical exercise$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What color should your pet's gums be?$q$, jsonb_build_array($q$Bubble gum pink$q$,$q$Dark red$q$,$q$Light pink$q$,$q$Almost white$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your pet has a significant cut, and blood has soaked through the gauze you are using to control the bleeding. You should...$q$, jsonb_build_array($q$Remove the soaked gauze and replace with a clean gauze$q$,$q$Remove the gauze and wash out the wound with clean water$q$,$q$Continue to add more gauze until the bleeding is under control or you are able to secure the bandage in place$q$,$q$Skip bleeding control and take your pet to the vet$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your cat slipped and fell a long way. Aside from a slightly injured leg, you believe they are fine. However, you know to watch out for shock. What signs will you look for?$q$, jsonb_build_array($q$Lethargy, extremely low heart rate, light gum color, cool extremities$q$,$q$Dilated pupils, frantic behavior, constant scratching$q$,$q$Loud yowling in the litter box and difficulty urinating$q$,$q$Extreme shedding and dilated pupils followed by increased aggression$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your animal has ingested toxins. After you get the go ahead from animal poison control to induce vomiting, the proper dose is...$q$, jsonb_build_array($q$2 tsp. of 3% hydrogen peroxide per 5 lbs of body weight$q$,$q$1 tsp. of 5% hydrogen peroxide per 10 lbs of body weight$q$,$q$1 tsp. of 3% hydrogen peroxide per 10 lbs of body weight$q$,$q$5 tsp. of 3% hydrogen peroxide per 8 lbs of body weight$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your pet is normally very excited to greet you when you get home, but today they did not greet you. When you found them, they were lying down and appeared very lethargic. You should...$q$, jsonb_build_array($q$Be suspicious that something might be wrong and take their vital signs$q$,$q$Be upset, because they are clearly not happy to see you$q$,$q$Wait and see how they act tomorrow$q$,$q$Rouse them and let them outside$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$After playing outside on a warm day, you notice your pet is lethargic. You take their temperature and see it is low. Which of the following is most likely true?$q$, jsonb_build_array($q$Your pet is experiencing heat stroke and you should cool them$q$,$q$Your pet has a fever and you should rush them to the vet as soon as possible$q$,$q$Your pet has hypothermia from poor circulation and you should quickly transport them to the vet$q$,$q$Your pet is dehydrated and you should get them water$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$You suspect your dog or cat has suffered a burn. After you make sure the scene is safe you should...$q$, jsonb_build_array($q$Check vital signs and then wrap the burn wound with gauze$q$,$q$Apply ice to the burn wound$q$,$q$Check vital signs. If breathing is okay, cool off burn area with cool water, wrap in a blanket or towel, and transport them for further care.$q$,$q$Immediately hose down your animal$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What are the differences in how you would treat fever and heat stroke?$q$, jsonb_build_array($q$You cool for both instances if your pet's temperature is higher than normal$q$,$q$You would warm your pet in both instances because your pet's body wants to warm itself$q$,$q$You would give your pet Tylenol for fever and ibuprofen for heatstroke$q$,$q$You should cool your pet to combat heat stroke; you should not cool your pet if it is combating fever$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$One of the most common poisonings in cats is the inadvertent topical application of...$q$, jsonb_build_array($q$Canine flea medication$q$,$q$Dish soap$q$,$q$Pet dewormer for cats$q$,$q$Shampoo$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What are some common signs your cat or dog has been poisoned?$q$, jsonb_build_array($q$Hair loss, red skin, and raised bumps$q$,$q$Drooling, vomiting, diarrhea, stumbling, muscle twitching, depression, hyperactivity, seizures, unconsciousness, or bleeding of mouth or skin$q$,$q$Pain, facial swelling, or hives$q$,$q$Drunken sailor gait$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What are some elements that may cause long-standing allergies to flare up?$q$, jsonb_build_array($q$Common food$q$,$q$Insect stings or bites$q$,$q$Pain, facial swelling, hives, or vomiting$q$,$q$Foods, grasses, or pollens$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the correct hand placement to begin compressions on a dog 25 lbs or bigger?$q$, jsonb_build_array($q$Place your thumb and fingers on either side of the chest and squeeze$q$,$q$One hand on the lower part of chest$q$,$q$One hand on top of the other hand, on the widest part of the chest closest to spine$q$,$q$One hand over the other hand, on top of the stomach$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the role of pet first aid?$q$, jsonb_build_array($q$To replace veterinary care$q$,$q$To help me open my own vet clinic$q$,$q$To help my pet as much as I can before veterinary care$q$,$q$To save money on vet bills$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
-- Spreadsheet question bank (Answer column converted from 1-based to 0-based)
($q$True or False: Pet First Aid will almost always replace the need for veterinary care$q$, jsonb_build_array($q$True$q$,$q$False$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Which of the following is NOT a sign of aggression in dogs?$q$, jsonb_build_array($q$Cowering$q$,$q$Exposing Belly$q$,$q$Urinating$q$,$q$Lip Smacking$q$,$q$raised fur$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Which of the following is NOT a sign of aggression in cats?$q$, jsonb_build_array($q$Raised Fur$q$,$q$Flattened Ears$q$,$q$flicking the tail$q$,$q$Gently purring$q$,$q$moving away$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the resting heartrate range for a relaxed dog at home?$q$, jsonb_build_array($q$40-100 bpm$q$,$q$80-140 bpm$q$,$q$60-120 bpm$q$,$q$75-130 bpm$q$,$q$35-90 bpm$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the normal body temperature range for cats and dogs?$q$, jsonb_build_array($q$98-101F$q$,$q$97-102F$q$,$q$99.5-102F$q$,$q$98.6-101.3F$q$,$q$92-99F$q$), 2, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: You can tell the wellness of your pet based on the moisture level of the nose?$q$, jsonb_build_array($q$True$q$,$q$False$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Which of the following are NOT signs of Bloat/GDV?$q$, jsonb_build_array($q$Excessive Drooling$q$,$q$Attempted Vomiting$q$,$q$Distended Midsection$q$,$q$Vital Sign Abnormality$q$,$q$All are signs of Bloat/GDV$q$), 4, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: When your pet vomits, this is a sign that you definitely need to take them to the vet?$q$, jsonb_build_array($q$True$q$,$q$False$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Which of the following common pets is most at risk for developing a urinary tract obstruction, thus requiring the most monitoring?$q$, jsonb_build_array($q$Male Dog$q$,$q$Male Cat$q$,$q$Female Dog$q$,$q$Female Cat$q$,$q$All are equally at risk$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: If your pet is experiencing muscle weakness and is diabetic, it's okay to rub syrup on their gums in case they're hypoglycemic?$q$, jsonb_build_array($q$True$q$,$q$False$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: If your pet has an abnormal temperature, you should look at your pet's behavior (if they are trying to warm or cool themselves) to determine how you can assist them prior to seeking veterinary assistance.$q$, jsonb_build_array($q$True$q$,$q$False$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: Cats are more prone to heat stroke than Dogs$q$, jsonb_build_array($q$True$q$,$q$False$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your dog is hit by a slow moving car and immediately gets up and seems to be fine. Later, you notice that he is very lethargic. You take his vital signs. His heart rate is 150 BPM, his gums are a light pink, and his ear tips feel cool. These are signs of...$q$, jsonb_build_array($q$Fever$q$,$q$Shock$q$,$q$Concussion$q$,$q$Dehydration$q$,$q$Heat Stroke$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$Your pet is limping oddly. When you feel his limbs, there's no wound or pain response. What should you be concerned about here?$q$, jsonb_build_array($q$Malnutrition$q$,$q$Neurological Lameness$q$,$q$Diabetes$q$,$q$Depression$q$,$q$Dislocation$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$The easiest way to transport a larger animal that can't move is finding a person to help you. Once you have the animal muzzled, you should...$q$, jsonb_build_array($q$Safely and swiftly move the animal onto a blanket or board to transport it to the vehicle$q$,$q$Put a towel under the belly of the animal and walk it toward the vehicle$q$,$q$Roll your animal to the vehicle$q$,$q$Wait for help to arrive$q$,$q$Begin CPR$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: If your pet has ingested toxins, it is always recommended to induce vomiting$q$, jsonb_build_array($q$True$q$,$q$False$q$), 1, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$You notice your dog or cat in the vicinity of a snake and suspect a bite may have occurred. What next steps are NOT recommended?$q$, jsonb_build_array($q$Try to take a picture of the snake without putting yourself in harm's way$q$,$q$Take your pet to your veterinary facility$q$,$q$Monitor your pet's vital signs$q$,$q$Apply tourniquet and ice, and attempt to suck the venom out$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: When administering abdominal thrusts, you can position large dogs either on their side on the floor or standing on all four legs$q$, jsonb_build_array($q$True$q$,$q$False$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$What is the optimal position to use when performing abdominal thrusts on a small dog who is choking?$q$, jsonb_build_array($q$Have her lying down on her right side$q$,$q$Have her lying down on her back with her paws in the air$q$,$q$Hold her in a ball in your arms$q$,$q$Hold her so her spine is braced against your chest and her hind legs are on the floor$q$,$q$Have her lying down on her left side$q$), 3, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: Your pet does not seem to be having any problems after being submerged in water; however, it is still a good idea to get it evaluated by a veterinarian.$q$, jsonb_build_array($q$True$q$,$q$False$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$),
($q$True or False: Signs your pet may be experiencing cardiac arrest are: loss of consciousness, no breathing or agonal breaths, and no pulse$q$, jsonb_build_array($q$True$q$,$q$False$q$), 0, $q$Refer to the Pet First Aid course materials for additional context.$q$, $q$Pet First Aid$q$);

commit;
